### PR TITLE
Basic ws support

### PR DESCRIPTION
**Pull request by dimapaloskin**
Hello.

This PR brings websockets proxying support.

### CODE REVIEW

**Comment by arunoda** [comment]
@dimapaloskin this is great.
Can we have a test case for this?

**Comment by dimapaloskin** [comment]
@arunoda Sure. Will do that.

**Comment by dimapaloskin** [comment]
@arunoda I added basic tests. I could not think of more test cases :)

**Comment by arunoda** [comment]
Thanks @dimapaloskin 
This looks great.

**Comment by iamstarkov** [comment]
sorry for late question, but how would one use it?

**Pull request merged**
