### PR TITLE
Add support for appending headers to request

### PR DESCRIPTION
**Pull request by lukas-valenta**

### CODE REVIEW

**Comment by pauldariye** [comment]
@lukas-valenta, great work on this. You have a conflict that may be preventing the `pr` getting accepted

**Comment by lukas-valenta** [comment]
@pauldariye fixed :+1:

**Comment by pauldariye** [comment]
Thanks, @lukas-valenta. @leo any thoughts? This would present a more elegant solution to the issue I reported here with CloudFlare https://spectrum.chat/thread/ae2061bb-8616-4c41-bdb7-523dd156b506

**Comment by rauchg** [comment]
Seems like a good idea. If you're still interested, please re-open and document `headers` in `README`

**Comment by pauldariye** [comment]
I'm happy to take this on @lukas-valenta. @rauchg I'll reopen this

**Comment by lukas-valenta** [comment]
@pauldariye OK

**Pull request closed without merging**
