### PR TITLE
Forward original status code

### LINKED ISSUE #10: Response from proxy always has 200 status code
Hi. As title says I always get 200 status code from proxy. The response body is fine, only status code changes to 200. 
If I do request directly to service - it works correct.
**For example:**
-service responce:
https://gyazo.com/07d511039c23e20c0f26a4b0b0d10918
-proxy-responce:
https://gyazo.com/af69691ec367fd27460a831fd291a856
What it may be?

### PR DESCRIPTION
**Pull request by dimapaloskin**
Fix #10

### CODE REVIEW

**Comment by dimapaloskin** [comment]
@arunoda could you review this PR? Looks like this is important bug :)

**Comment by jimthedev** [comment]
I can confirm that this fixes a bug that shows up when putting superstatic behind the proxy. You get issues like this:

```
Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:494:11)
    at ServerResponse.setHeader (_http_outgoing.js:501:3)
    at Responder.handleFileStream (/Users/jcummins/projects/moonsheets.com/node_modules/superstatic/lib/responder.js:115:12)
    at /Users/jcummins/projects/moonsheets.com/node_modules/superstatic/lib/responder.js:103:17
    at tryCatch (/Users/jcummins/projects/moonsheets.com/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/jcummins/projects/moonsheets.com/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/Users/jcummins/projects/moonsheets.com/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/Users/jcummins/projects/moonsheets.com/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

Which are resolved when using @dimapaloskin's fork.

**Comment by dimapaloskin** [comment]
@jimthedev Hey, mate. Looks like a lot of those  guys (@rauchg , @leo , @arunoda ) can **just** write blog posts about open source, no more

**Comment by jimthedev** [comment]
@dimapaloskin I think they've given **quite** a lot back to OSS in very real terms. One might say they've dedicated their lives and careers to it. It is the holidays so let's give them a break to be with family, right?

**Comment by dimapaloskin** [comment]
@jimthedev I agree. Sorry. Waiting...

**Comment by jimthedev** [comment]
💯 Thanks for the PR btw.

**Comment by dimapaloskin** [comment]
So qute

**Comment by leo** [comment]
Thanks! Definitely a great addition 😊 Went out with the latest release.

**Pull request merged**
